//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formular
    {
        public int formular_id { get; set; }
        public string ticket { get; set; }
        public Nullable<System.DateTime> book_delivery { get; set; }
        public Nullable<System.DateTime> book_reception { get; set; }
        public Nullable<System.DateTime> book_return { get; set; }
        public Nullable<int> book_id { get; set; }
    
        public virtual books books { get; set; }
    }
}
